//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_assignment
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Required]
        public int employeeId { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string department { get; set; }
        [Required]
        public Nullable<int> salary { get; set; }
        [Required]
        public string designation { get; set; }
        [Required]
        //[Compare("employeeId", ErrorMessage ="ManagerId and EmployeeId should not be same.")]

        public Nullable<int> managerId { get; set; }


    }
}
